DROP TABLE public.patient CASCADE;
DROP TABLE public.visit CASCADE;
DROP TABLE public.prescription CASCADE;
DROP TABLE public.doctor CASCADE;
DROP TABLE public.specialization CASCADE;
DROP TABLE public.test CASCADE;
DROP TABLE public.laboratory CASCADE;
DROP TABLE public.technician CASCADE;
DROP TABLE public.doctor_specialization CASCADE;